name: CI / Automated testing
on:
  push:
    branches: ["**"]

jobs:
  test:
    runs-on: ubuntu-20.04
    name: Elixir ${{ matrix.elixir }} OTP ${{ matrix.otp }}
    env:
      MIX_ENV: test

    strategy:
      # https://hexdocs.pm/elixir/1.14/compatibility-and-deprecations.html#compatibility-between-elixir-and-erlang-otp
      matrix:
        elixir: [1.12.x, 1.14.x]
        otp: [23.x, 25.x]
        exclude:
          - elixir: 1.12.x
            otp: 25.x
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{ matrix.otp }}
          elixir-version: ${{ matrix.elixir }}
      - name: Cache deps
        uses: actions/cache@v3
        with:
          path: |
            deps
            _build
          key: deps-cache-${{ matrix.elixir }}-${{ matrix.otp }}-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            deps-cache-${{ matrix.elixir }}-${{ matrix.otp }}-
      - name: Install dependencies
        run: mix do local.hex --force, local.rebar --force, deps.get
      - name: Check code formatting
        run: mix format --check-formatted
      - name: Compile dependencies
        run: mix deps.compile
      - name: Compile code (warnings as errors)
        run: mix compile --warnings-as-errors
      - name: Run tests
        run: mix test
      - name: Create docs
        run: mix docs
